/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestaofuncionarios.view;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author logcomex
 */
public class FuncionarioView extends javax.swing.JInternalFrame {

        /**
         * Creates new form NewJInternalFrame
         */
        public FuncionarioView() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                lblNome = new javax.swing.JLabel();
                txtNome = new javax.swing.JTextField();
                lblCargo = new javax.swing.JLabel();
                txtCargo = new javax.swing.JTextField();
                lblSalarioBase = new javax.swing.JLabel();
                txtSalarioBase = new javax.swing.JTextField();
                jSeparator1 = new javax.swing.JSeparator();
                lblFaltas = new javax.swing.JLabel();
                lblDistancia = new javax.swing.JLabel();
                txtFaltas = new javax.swing.JTextField();
                txtDistancia = new javax.swing.JTextField();
                btnFechar = new javax.swing.JButton();
                btnVerBonus = new javax.swing.JButton();
                btnExcluir = new javax.swing.JButton();
                btnEditar = new javax.swing.JButton();
                btnSalvar = new javax.swing.JButton();

                lblNome.setText("Nome");

                lblCargo.setText("Cargo");

                lblSalarioBase.setText("Salário Base");

                lblFaltas.setText("Faltas");

                lblDistancia.setText("Distancia");

                btnFechar.setText("Fechar");

                btnVerBonus.setText("Ver Bonus");

                btnExcluir.setText("Excluir");

                btnEditar.setText("Editar");

                btnSalvar.setText("Salvar");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jSeparator1)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(lblCargo)
                                                                                                                .addComponent(lblNome))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(txtNome)
                                                                                                                .addComponent(txtCargo)))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(lblSalarioBase)
                                                                                                                                .addComponent(lblFaltas)
                                                                                                                                .addComponent(lblDistancia))
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(txtSalarioBase)
                                                                                                                                .addComponent(txtFaltas)
                                                                                                                                .addComponent(txtDistancia)))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(0, 21, Short.MAX_VALUE)
                                                                                                                .addComponent(btnEditar)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                .addComponent(btnExcluir)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                .addComponent(btnVerBonus)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                .addComponent(btnSalvar)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                .addComponent(btnFechar)))
                                                                .addContainerGap()));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lblNome)
                                                                                .addComponent(txtNome,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lblCargo)
                                                                                .addComponent(txtCargo,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jSeparator1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                10,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lblSalarioBase)
                                                                                .addComponent(txtSalarioBase,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(lblFaltas)
                                                                                .addComponent(txtFaltas,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(lblDistancia)
                                                                                .addComponent(txtDistancia,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnFechar)
                                                                                .addComponent(btnVerBonus)
                                                                                .addComponent(btnExcluir)
                                                                                .addComponent(btnEditar)
                                                                                .addComponent(btnSalvar))
                                                                .addGap(19, 19, 19)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        public JButton getBtnEditar() {
                return btnEditar;
        }

        public JButton getBtnExcluir() {
                return btnExcluir;
        }

        public JButton getBtnFechar() {
                return btnFechar;
        }

        public JButton getBtnSalvar() {
                return btnSalvar;
        }

        public JButton getBtnVerBonus() {
                return btnVerBonus;
        }

        public JTextField getTxtCargo() {
                return txtCargo;
        }

        public JTextField getTxtDistancia() {
                return txtDistancia;
        }

        public JTextField getTxtFaltas() {
                return txtFaltas;
        }

        public JTextField getTxtNome() {
                return txtNome;
        }

        public JTextField getTxtSalarioBase() {
                return txtSalarioBase;
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnEditar;
        private javax.swing.JButton btnExcluir;
        private javax.swing.JButton btnFechar;
        private javax.swing.JButton btnSalvar;
        private javax.swing.JButton btnVerBonus;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JLabel lblCargo;
        private javax.swing.JLabel lblDistancia;
        private javax.swing.JLabel lblFaltas;
        private javax.swing.JLabel lblNome;
        private javax.swing.JLabel lblSalarioBase;
        private javax.swing.JTextField txtCargo;
        private javax.swing.JTextField txtDistancia;
        private javax.swing.JTextField txtFaltas;
        private javax.swing.JTextField txtNome;
        private javax.swing.JTextField txtSalarioBase;
        // End of variables declaration//GEN-END:variables
}
